# Usa uma imagem Python leve
FROM python:3.9-slim

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos da API para dentro do container
COPY . /app

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Define a porta que a API vai usar
EXPOSE 5000

# Comando para rodar a API Flask
CMD ["python", "app.py"]
